import Head from "next/head"
import React from "react"

function Button() {
  return (
    <div>
      <Head>
        <title>Fonts, Size and Letter Spacing in Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center mt-48">
        <button className="bg-indigo-400 text-white px-4 py-4">Upload Image</button>
      </div>

      <div className="flex justify-center items-center mt-48">
        <button className="bg-indigo-400 text-white px-4 py-4">Download New Image</button>
      </div>
    </div>
  )
}

export default Button

